/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Q3 {
    public boolean search(int[][] array, int number) {
        int rs = array.length;
        int cs = array[0].length;
        int r = 0;
        int c = cs - 1;

        while (c >= 0 && r < rs) {
            if (number < array[r][c]) {
                c--;
            } else if (number == array[r][c]) {
                return true;
            } else {
                r++;
            }
        }

        return false;
    }
}
