/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.testng.Assert;
import org.testng.annotations.DataProvider;
import org.testng.annotations.Test;

public class Q3Test {
    @DataProvider(name = "search")
    public Object[][] createSearchData() {
        return new Object[][]{
                {
                        new int[][]{
                                {1, 2, 8, 9},
                                {2, 4, 9, 12},
                                {4, 7, 10, 13},
                                {6, 8, 11, 15},
                        },
                        7,
                        true,
                },
                {
                        new int[][]{
                                {1, 2, 8, 9},
                                {2, 4, 9, 12},
                                {4, 7, 10, 13},
                                {6, 8, 11, 15},
                        },
                        5,
                        false,
                }
        };
    }

    @Test(dataProvider = "search")
    public void testSearch(int[][] array, int number, boolean want) {
        Q3 t = new Q3();
        boolean got = t.search(array, number);
        Assert.assertEquals(got, want);
    }
}
